import Head from "next/head";
import useAuth from "./hooks/useAuth";
import WithPrivateRoute from "./components/navigation/withPrivateRoute";
import { Button, Col, Container, Row } from "react-bootstrap";
export default function Home() {
  const { signOut } = useAuth();
  return (
    <WithPrivateRoute>
      <Head>
        <title>Connected Wealth</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="mt-3">
        <Row className="justify-content-end">
          <Button className="w-auto" onClick={signOut}>
            Logout
          </Button>
        </Row>
        <Row>
          <Col></Col>
        </Row>
      </Container>
    </WithPrivateRoute>
  );
}
